# Generated by Django 4.1.6 on 2023-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Division', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('DateToAdd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
