# Generated by Django 4.1.6 on 2023-11-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_postnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmembers',
            old_name='DateToAdd',
            new_name='dateToAdd',
        ),
        migrations.RenameField(
            model_name='addmembers',
            old_name='Division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='addmembers',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='addmembers',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='addmembers',
            old_name='LastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='addmembers',
            old_name='PhoneNumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='postnews',
            old_name='TextToPost',
            new_name='texttopost',
        ),
    ]
