# Generated by Django 4.1.6 on 2023-11-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_phonenumber_addmembers_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMembers',
            new_name='Members',
        ),
    ]
