# Generated by Django 4.1.6 on 2023-11-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_postnews_texttopost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostNews',
        ),
    ]
