# Generated by Django 4.1.6 on 2023-11-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='division',
            field=models.CharField(choices=[('dev', 'dev'), ('cpd', 'cpd'), ('cbd', 'cbd')], max_length=200, null=True),
        ),
    ]
